#!/bin/bash

PATH=$PATH:/usr/local/lib/python3.9/dist-packages/mpy_cross

if [ "$1" = "-c" ] || [ "$1" = "-s" ]
then
	for f in lib/*.py
	do
		mpy-cross -O3 -march=xtensa $f
	done
fi

if [ "$1" = "-m-esp32" ]
then
	python3 -m esptool --chip esp32 --port /dev/ttyUSB0 erase_flash
	python3 -m esptool --chip esp32 --port /dev/ttyUSB0 --baud 460800 write_flash --flash_size=detect -z 0x1000 esp32.bin
fi

if [ "$1" = "-m-esp8266" ]
then
	python3 -m esptool --chip esp8266 --port /dev/ttyUSB0 erase_flash
	python3 -m esptool --chip esp8266 --port /dev/ttyUSB0 --baud 460800 write_flash --flash_size=detect -fm dio 0 esp8266.bin
fi

if [ "$1" = "-s" ]
then
	mpfshell ttyUSB0 -s server.mpf
fi

if [ "$1" = "-c" ]
then
	mpfshell ttyUSB0 -s client.mpf
fi

if [ "$1" = "-c" ] || [ "$1" = "-s" ]
then
	rm lib/*.mpy
fi

if [ "$2" = "-r" ]
then
	mpfshell ttyUSB0 -c repl
fi
